### ISSUE TITLE
Some SSLException variants can be transient and should be retried

### ISSUE THREAD

**Issue by guperrot** [Microsoft/mobile-center-sdk-android#270]
![download](https://cloud.githubusercontent.com/assets/623672/20897463/50ac135c-bad7-11e6-8d59-4905932ade9f.png)

This exception should be retried as part of the existing http retry logic.

**Comment by Khoosham** [comment]
thanks for opening the issue i sent you hope it gets resolve soon :)

**Comment by guperrot** [comment]
Will be part of 0.3.3 release.

**Comment by guperrot** [comment]
@Khoosham can you test the fix by using this repository in your gradle config:

```

**Comment by Khoosham** [comment]
i tried the fix its not showing the error anymore. maybe i could not reproduce it or the fix is working.
will let u know if ever i get it again.

**Comment by guperrot** [comment]
@Khoosham Hi, the fix is working as the error is now retried. We cannot prevent transient errors from happening but the fix is to retry those.

Can you check that logs gets eventually sent after retrying?

**Comment by Khoosham** [comment]
did it fail to send ?
i got this
http://prntscr.com/dhqnmi

**Comment by guperrot** [comment]
If it's a warning, it is retried, if it's an error, we abort.
I need to add this new error to the list of what we can retry as its considered a fatal error now.
Again, it seems like a temporary issue when connection is unstable, so even after the fix you will see a warning instead of an error and then a retry later.

**Comment by guperrot** [comment]
Hi @Khoosham , I added one more retry scenario for the last exception you mentioned in this thread.

Can you:

- Verify the behavior on version `0.3.3-16+a060ba5`.
- Call MobileCenter.setLogLevel(Log.VERBOSE); and check it gets eventually retried (successful HTTP logs will be only displayed in verbose).
- You can also check "Log flow" under "Analytics" on portal to see incoming individual logs.

Thanks in advance.

**Comment by guperrot** [comment]
You can actually test on official version 0.3.3 now, we released some fixes.

**Comment by Khoosham** [comment]
i think its working now response 200ok

Try #1 failed and will be retried in 6316 ms
java.io.EOFException at libcore.io.Streams.readAsciiLine(Streams.java:203)
at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:579)
atlibcore.net.http.HttpEngine.readResponse(HttpEngine.java:827)................


http://prntscr.com/djmrpl

**Comment by guperrot** [comment]
EOFException is already retried indeed.
Will close issue now, thanks for using Mobile Center.
