### ISSUE TITLE
Failed to get service instance 'com.microsoft.azure.mobile.crashes.Crashes', skipping it. using pro guard

### ISSUE THREAD

**Issue by khalid-mahmood** [Microsoft/mobile-center-sdk-android#304]
unable to view crashes if pro guard is used getting this message in error log
Failed to get service instance 'com.microsoft.azure.mobile.crashes.Crashes', skipping it.
pro guard settings ?
 without pro guard working

**Comment by guperrot** [comment]
Hi, we will look at proguard settings in details soon.

In the mean time, you can try to keep the `Crashes.getInstance` method (same for `Analytics.getInstance`), we call it via reflection and that's probably what Proguard removed.

**Comment by guperrot** [comment]
#305 addresses the issue and will embed the rules automatically.

While waiting for the version 0.4.0 of our SDK you can use this rule in the current version to fix your application:

```

**Comment by khalid-mahmood** [comment]
just keep everything as it is.. fix for me.
-keep class com.microsoft.** { *; }

**Comment by guperrot** [comment]
@khalid-mahmood the version 0.4.0 embeds the proguard configuration inside the library so you can remove the rules after upgrading.

**Comment by dfoulk** [comment]
I've run into this issue with Microsoft.AppCenter v1.1.0. Perhaps the fix did not get updated with the new namespace?

**Comment by dfoulk** [comment]
After adding `-keep class com.microsoft.appcenter.**` to **proguard.cfg**, my app compiled and ran without exceptions. For whatever reason, I remove that line and the exception does not return? Anyways, that's how I worked around this issue.

I can't remember the exception exactly- but it had to do with resolving an interface (ICrash...) or something.

**Comment by guperrot** [comment]
Having the exact exception would allow us to preserve the classes that cause issues. If you can reproduce that would be helpful as our test apps don't need any additional proguard rules. Also the .NET repository is https://github.com/Microsoft/AppCenter-SDK-DotNet if you can create the issue there as apparently you use Xamarin.

**Comment by dfoulk** [comment]
Of course. I was attempting to obtain that exception message when I discovered that I could not get it to output that exception again. I will be sure to post in the other repo when I see that exception again. Thanks @guperrot

**Comment by dfoulk** [comment]
> Unable to resolve interface type 'Com.Microsoft.Appcenter.Crashes.ICrashesListener'. Are you missing an assembly reference?

This exception is only thrown when building the Android project of my Xamarin.Forms app. That being said, I will still post in the other repo if you feel that it is the right place for this.

Thanks,
-Derek

**Comment by guperrot** [comment]
Sure, but we also need more details anyway than just this message alone. packages.config for Android project if any, csproj for the Android project, build logs in diagnostic log level.
