### ISSUE TITLE
Custom event property is not showing up 

### ISSUE THREAD

**Issue by alifarina** [Microsoft/mobile-center-sdk-android#354]
I am trying to send a Http url and a HTML content in two different properties of a custom event .

There are three other properties as well . Out of the five only these three with simple data as string are showing up on the Analytics page . Other two properties with Http url and HTML content is not showing.

I can see the property in Log Flow of Mobile Center but not in Events page.

**Comment by guperrot** [comment]
Hi, this is not a SDK issue if you can see everything in log flow.

@alifarina Can you open a ticket to our support center by clicking on the blue button in bottom right corner on the portal?

**Comment by alifarina** [comment]
ok , thanks
