### ISSUE TITLE
Distribute: Failed to enable in app-updates

### ISSUE THREAD

**Issue by carlos-ferreira** [Microsoft/mobile-center-sdk-android#389]
On my app i followed the guide on github but when i open my app, a browser window opens with the following message "Failed to enable in app-updates".
Also, reinstalling the app doesn't make any difference.

![screenshot_2017-03-31-10-52-15](https://cloud.githubusercontent.com/assets/472873/24545833/bc66540c-1600-11e7-8c13-0c449b270db6.png)

**Comment by guperrot** [comment]
Hi, it will always fail if you don't install the application from the email. We don't support side loading scenario for now.

When you distribute the application via Mobile Center, you will receive an email and you need to install the application from the Mobile Center web site linked from that email.

**Comment by carlos-ferreira** [comment]
I can confirm your "solution".
Maybe this should be explicit somewhere on the docs or did i missed it ?

**Comment by guperrot** [comment]
Hi, the documentation will be improved as it's indeed lacking context on how the distribute feature works in Mobile Center.

**Comment by guperrot** [comment]
@carlos-ferreira we tried to improve the documentation, please check https://docs.microsoft.com/en-us/mobile-center/sdk/distribute/android#how-do-in-app-updates-work
