### ISSUE TITLE
Xamarin.Forms/Xamarin.Android: Distribute.DontCheckForUpdatesInDebug() not available

### ISSUE THREAD

**Issue by Dids** [Microsoft/mobile-center-sdk-android#409]
This is more of a question, but what is the reasoning behind not having `Distribute.DontCheckForUpdatesInDebug()` available when targeting Android in Xamarin.Forms/Xamarin.Android?

Does it do that automatically, or should I check if I'm running a debug build and disable Distribute manually?

**Comment by guperrot** [comment]
Hi, Android disables distribute on debug automatically.

**Comment by Dids** [comment]
Thank you, didn't see this mentioned in the docs (at a quick glance at least), but glad to hear it. :)
